apiVersion: v1
kind: Service
metadata:
  name: {{ include "myservice.name"  . }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "myservice.name"  . }}
  ports:
    - port: {{ .Values.ports.ingress_port }}
      targetPort: {{ .Values.ports.container_port }}